spring.application.name=SLICGL_Inter_Bank_Transfer_Management
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/slicll_ibt_management
spring.datasource.username=root
spring.datasource.password=Root
# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate Configuration (JPA)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
# Enable Liquibase for controlled migrations
spring.liquibase.enabled=true
# Add validation
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
frontend.url=http://localhost:3000/
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=edirisooriyaakila@gmail.com
spring.mail.password=khksrobogqndimyj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.transaction=DEBUG
logging.level.SLICGL.example.SLICGL_Inter_Bant_Transfer_Management=DEBUG
server.servlet.session.timeout=15m

